### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/github-comment#1]

**Comment by siddharthkp** [comment]
hi

**Comment by siddharthkp** [comment]
comment 1510219870265

**Comment by siddharthkp** [comment]
comment 1510221288971

**Comment by siddharthkp** [comment]
comment 1510221434794

**Comment by meetzaveri** [comment]
Is this dummy repo? Because I have subscribed this repo to notice progress @siddharthkp .

**Comment by siddharthkp** [comment]
@meetzaveri, nope not dummy

Just pushed all the code 😄
Check out the readme

You might want to unsubscribe from this issue though 😄

**Comment by siddharthkp** [comment]
comment 1510222100803

**Comment by meetzaveri** [comment]
Okay I'll unsubscribe from the issue, yo saw the code it's hecking awesome. Saw you on freindsHasGeek slack community! @siddharthkp

**Comment by siddharthkp** [comment]
comment 1510222509991

**Comment by siddharthkp** [comment]
comment 1510222575702

**Comment by siddharthkp** [comment]
comment 1510222598750

**Comment by siddharthkp** [comment]
comment 1510222605157

**Comment by siddharthkp** [comment]
comment 1510227461781

**Comment by billiegoose** [comment]
## Test results

| Browser | Pass | Skip | Fail |
|---|---|---|---|
| Chrome | 204 | 4 | 0 |
| Edge | 180 | 4 | 0 |
| Firefox | 204 | 4 | 0 |

Time elapsed: 12 minutes

**Comment by siddharthkp** [comment]
@wmhilton 😄

**Comment by billiegoose** [comment]
Thank you @siddharthkp for this awesome module! I put it to good use as a custom test reporter: https://github.com/isomorphic-git/isomorphic-git/pull/435#issuecomment-418848055

**Comment by meetzaveri** [comment]
Good use of the resource!
